#ifndef LIS3DH_CONFIG_H
#define LIS3DH_CONFIG_H

#include "sdkconfig.h"

#define LIS3DH_I2C_SDA_PIN      CONFIG_LIS3DH_I2C_SDA_PIN
#define LIS3DH_I2C_SCL_PIN      CONFIG_LIS3DH_I2C_SCL_PIN
#define LIS3DH_I2C_CLK_SPEED    CONFIG_LIS3DH_I2C_CLK_SPEED
#define LIS3DH_I2C_ADDRESS      CONFIG_LIS3DH_I2C_ADDRESS

#endif /* LIS3DH_CONFIG_H */
