name: 'Build Component Examples'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    name: Build examples with ESP-IDF ${{ matrix.idf_ver }} for ${{ matrix.idf_target }}
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["release-v5.3", "release-v5.4", "release-v5.5"]
        idf_target: ["esp32", "esp32s3", "esp32c3", "esp32c6"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install idf-build-apps
      shell: bash
      run: |
        . ${IDF_PATH}/export.sh
        python3 -m pip install idf-build-apps==2.4.3

    - name: Build examples for ${{ matrix.idf_target }}
      shell: bash
      run: |
        . ${IDF_PATH}/export.sh
        idf-build-apps build --target ${{ matrix.idf_target }} --recursive --build-dir build_${{ matrix.idf_target }}

  build-ultraled:
    name: Build Ultraled with ESP-IDF 6.0 for ESP32-P4
    runs-on: ubuntu-22.04
    container: espressif/idf:release-v6.0
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build Ultraled example and test applications
      shell: bash
      run: |
        . ${IDF_PATH}/export.sh
        idf.py -C ultraled/examples/ultraled_basic set-target esp32p4
        idf.py -C ultraled/examples/ultraled_basic build
        idf.py -C ultraled/test_apps/ultraled set-target esp32p4
        idf.py -C ultraled/test_apps/ultraled build
        idf.py -C ultraled/test_apps/ultraled_perf set-target esp32p4
        idf.py -C ultraled/test_apps/ultraled_perf build
        idf.py -C ultraled/test_apps/ultraled_selective set-target esp32p4
        idf.py -C ultraled/test_apps/ultraled_selective build
